name: pdfconverter
services:
  pdfconverter:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/healthcheck"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "1337:8080"
    # Required for rootless Docker
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /tmp:size=512M
    restart: always